### ISSUE TITLE
Fails to import a module, from itself

### ISSUE THREAD

**Issue by DarkZeros** [openai/baselines#27]
Traceback (most recent call last):
  File "pole_train.py", line 3, in <module>
    from baselines import deepq
  File "/usr/local/lib/python3.4/dist-packages/baselines/deepq/__init__.py", line 4, in <module>
    from baselines.deepq.simple import learn, load  # noqa
  File "/usr/local/lib/python3.4/dist-packages/baselines/deepq/simple.py", line 12, in <module>
    from baselines import deepq
ImportError: cannot import name 'deepq'

**Comment by siemanko** [comment]
Currently we have no way of reproducing this issue. If you are willing to provide simple means of reproducing this, such as docker image, we can look into this.

**Comment by Bhargav5** [comment]
You can replace,
from baselines import deepq by
from baselines.deepq.build_graph import build_act, build_train

it will work. This problem I faced while working with python 2.7
