### ISSUE TITLE
cannot import name 'deepq'

### ISSUE THREAD

**Issue by Dangerpuss** [openai/baselines#18]
On a fresh Debian GNU/Linux 3.16.0-4-amd64 install I tried:

wget https://bootstrap.pypa.io/get-pip.py
sudo python3.4 get-pip.py
sudo pip install baselines
python3.4 -m baselines.deepq.experiments.train_cartpole

Error: "/usr/bin/python3.4: Error while finding spec for 'baselines.deepq.experiments.train_cartpole' (<class 'ImportError'>: cannot import name 'deepq')"

I couldn't find any mention of deepq in the feedback from the installation.
[baselines_install_log.txt](https://github.com/openai/baselines/files/1043007/baselines_install_log.txt)

**Comment by siemanko** [comment]
I am not sure what happened there, but the file is definitely there. You can manually download the pypi archive and verify for yourself: https://pypi.python.org/pypi/baselines . Let me know if you find a problem there. As a temporary workaround you can clone the repo and run setup.py manually. 

It's also a duplicate of a previous issue so closing.

**Comment by erwincoumans** [comment]
I just ran into the same problem, odd.

**Comment by Dangerpuss** [comment]
You should be fine if you use Python 3.5 or higher. If that's not an option then I commented on another similar issue with some code that can fix it. Good Luck

**Comment by EderSantana** [comment]
I just got a similar problem even with python 3.6 tho

**Comment by Bhargav5** [comment]
You can replace,
from baselines import deepq by
from baselines.deepq.build_graph import build_act, build_train

it will work. This problem I faced while working with python 2.7

**Comment by erwincoumans** [comment]
Thanks, Bhargav5 that did the trick for Python 2.7
